export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const REQUEST_RESET_PASSWORD_REQUEST = "REQUEST_RESET_PASSWORD_REQUEST";
export const REQUEST_RESET_PASSWORD_SUCCESS = "REQUEST_RESET_PASSWORD_SUCCESS";
export const REQUEST_RESET_PASSWORD_FAILURE = "REQUEST_RESET_PASSWORD_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAILURE = "UPDATE_AVATAR_FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE";

export const ADD_AUTH_REQUEST = "ADD_AUTH_REQUEST";
export const ADD_AUTH_SUCCESS = "ADD_AUTH_SUCCESS";
export const ADD_AUTH_FAILURE = "ADD_AUTH_FAILURE";

export const EDIT_AUTH_REQUEST = "EDIT_AUTH_REQUEST";
export const EDIT_AUTH_SUCCESS = "EDIT_AUTH_SUCCESS";
export const EDIT_AUTH_FAILURE = "EDIT_AUTH_FAILURE";

export const DELETE_AUTH_REQUEST = "DELETE_AUTH_REQUEST";
export const DELETE_AUTH_SUCCESS = "DELETE_AUTH_SUCCESS";
export const DELETE_AUTH_FAILURE = "DELETE_AUTH_FAILURE";

export const GET_AUTH_BY_ID_REQUEST = "GET_AUTH_BY_ID_REQUEST";
export const GET_AUTH_BY_ID_SUCCESS = "GET_AUTH_BY_ID_SUCCESS";
export const GET_AUTH_BY_ID_FAILURE = "GET_AUTH_BY_ID_FAILURE";

export const FIND_AUTH_BY_KEYWORD_REQUEST = "FIND_AUTH_BY_KEYWORD_REQUEST";
export const FIND_AUTH_BY_KEYWORD_SUCCESS = "FIND_AUTH_BY_KEYWORD_SUCCESS";
export const FIND_AUTH_BY_KEYWORD_FAILURE = "FIND_AUTH_BY_KEYWORD_FAILURE";
