export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";

export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
export const ADD_BLOG_FAILURE = "ADD_BLOG_FAILURE";

export const EDIT_BLOG_REQUEST = "EDIT_BLOG_REQUEST";
export const EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS";
export const EDIT_BLOG_FAILURE = "EDIT_BLOG_FAILURE";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE";

export const GET_BLOG_BY_ID_REQUEST = "GET_BLOG_BY_ID_REQUEST";
export const GET_BLOG_BY_ID_SUCCESS = "GET_BLOG_BY_ID_SUCCESS";
export const GET_BLOG_BY_ID_FAILURE = "GET_BLOG_BY_ID_FAILURE";

export const FIND_BLOG_BY_KEYWORD_REQUEST = "FIND_BLOG_BY_KEYWORD_REQUEST";
export const FIND_BLOG_BY_KEYWORD_SUCCESS = "FIND_BLOG_BY_KEYWORD_SUCCESS";
export const FIND_BLOG_BY_KEYWORD_FAILURE = "FIND_BLOG_BY_KEYWORD_FAILURE";

export const FIND_BLOG_BY_SUBCATEGORY_ID_REQUEST = "FIND_BLOG_BY_SUBCATEGORY_ID_REQUEST";
export const FIND_BLOG_BY_SUBCATEGORY_ID_SUCCESS = "FIND_BLOG_BY_SUBCATEGORY_ID_SUCCESS";
export const FIND_BLOG_BY_SUBCATEGORY_ID_FAILURE = "FIND_BLOG_BY_SUBCATEGORY_ID_FAILURE";