export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE";

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAILURE = "EDIT_CONTACT_FAILURE";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";

export const GET_CONTACT_BY_ID_REQUEST = "GET_CONTACT_BY_ID_REQUEST";
export const GET_CONTACT_BY_ID_SUCCESS = "GET_CONTACT_BY_ID_SUCCESS";
export const GET_CONTACT_BY_ID_FAILURE = "GET_CONTACT_BY_ID_FAILURE";

export const FIND_CONTACT_BY_KEYWORD_REQUEST = "FIND_CONTACT_BY_KEYWORD_REQUEST";
export const FIND_CONTACT_BY_KEYWORD_SUCCESS = "FIND_CONTACT_BY_KEYWORD_SUCCESS";
export const FIND_CONTACT_BY_KEYWORD_FAILURE = "FIND_CONTACT_BY_KEYWORD_FAILURE";
