export const GET_MEDIA_REQUEST = "GET_MEDIA_REQUEST";
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS";
export const GET_MEDIA_FAILURE = "GET_MEDIA_FAILURE";

export const ADD_MEDIA_REQUEST = "ADD_MEDIA_REQUEST";
export const ADD_MEDIA_SUCCESS = "ADD_MEDIA_SUCCESS";
export const ADD_MEDIA_FAILURE = "ADD_MEDIA_FAILURE";

export const EDIT_MEDIA_REQUEST = "EDIT_MEDIA_REQUEST";
export const EDIT_MEDIA_SUCCESS = "EDIT_MEDIA_SUCCESS";
export const EDIT_MEDIA_FAILURE = "EDIT_MEDIA_FAILURE";

export const DELETE_MEDIA_REQUEST = "DELETE_MEDIA_REQUEST";
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS";
export const DELETE_MEDIA_FAILURE = "DELETE_MEDIA_FAILURE";

export const GET_MEDIA_BY_ID_REQUEST = "GET_MEDIA_BY_ID_REQUEST";
export const GET_MEDIA_BY_ID_SUCCESS = "GET_MEDIA_BY_ID_SUCCESS";
export const GET_MEDIA_BY_ID_FAILURE = "GET_MEDIA_BY_ID_FAILURE";

export const FIND_MEDIA_BY_KEYWORD_REQUEST = "FIND_MEDIA_BY_KEYWORD_REQUEST";
export const FIND_MEDIA_BY_KEYWORD_SUCCESS = "FIND_MEDIA_BY_KEYWORD_SUCCESS";
export const FIND_MEDIA_BY_KEYWORD_FAILURE = "FIND_MEDIA_BY_KEYWORD_FAILURE";
