export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const ADD_ORGANIZATION_REQUEST = "ADD_ORGANIZATION_REQUEST";
export const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
export const ADD_ORGANIZATION_FAILURE = "ADD_ORGANIZATION_FAILURE";

export const EDIT_ORGANIZATION_REQUEST = "EDIT_ORGANIZATION_REQUEST";
export const EDIT_ORGANIZATION_SUCCESS = "EDIT_ORGANIZATION_SUCCESS";
export const EDIT_ORGANIZATION_FAILURE = "EDIT_ORGANIZATION_FAILURE";

export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILURE = "DELETE_ORGANIZATION_FAILURE";

export const GET_ORGANIZATION_BY_ID_REQUEST = "GET_ORGANIZATION_BY_ID_REQUEST";
export const GET_ORGANIZATION_BY_ID_SUCCESS = "GET_ORGANIZATION_BY_ID_SUCCESS";
export const GET_ORGANIZATION_BY_ID_FAILURE = "GET_ORGANIZATION_BY_ID_FAILURE";

export const FIND_ORGANIZATION_BY_KEYWORD_REQUEST = "FIND_ORGANIZATION_BY_KEYWORD_REQUEST";
export const FIND_ORGANIZATION_BY_KEYWORD_SUCCESS = "FIND_ORGANIZATION_BY_KEYWORD_SUCCESS";
export const FIND_ORGANIZATION_BY_KEYWORD_FAILURE = "FIND_ORGANIZATION_BY_KEYWORD_FAILURE";
