export const GET_SKILL_REQUEST = "GET_SKILL_REQUEST";
export const GET_SKILL_SUCCESS = "GET_SKILL_SUCCESS";
export const GET_SKILL_FAILURE = "GET_SKILL_FAILURE";

export const ADD_SKILL_REQUEST = "ADD_SKILL_REQUEST";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const ADD_SKILL_FAILURE = "ADD_SKILL_FAILURE";

export const EDIT_SKILL_REQUEST = "EDIT_SKILL_REQUEST";
export const EDIT_SKILL_SUCCESS = "EDIT_SKILL_SUCCESS";
export const EDIT_SKILL_FAILURE = "EDIT_SKILL_FAILURE";

export const DELETE_SKILL_REQUEST = "DELETE_SKILL_REQUEST";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAILURE = "DELETE_SKILL_FAILURE";

export const GET_SKILL_BY_ID_REQUEST = "GET_SKILL_BY_ID_REQUEST";
export const GET_SKILL_BY_ID_SUCCESS = "GET_SKILL_BY_ID_SUCCESS";
export const GET_SKILL_BY_ID_FAILURE = "GET_SKILL_BY_ID_FAILURE";

export const FIND_SKILL_BY_KEYWORD_REQUEST = "FIND_SKILL_BY_KEYWORD_REQUEST";
export const FIND_SKILL_BY_KEYWORD_SUCCESS = "FIND_SKILL_BY_KEYWORD_SUCCESS";
export const FIND_SKILL_BY_KEYWORD_FAILURE = "FIND_SKILL_BY_KEYWORD_FAILURE";
