export const GET_SUBCATEGORY_REQUEST = "GET_SUBCATEGORY_REQUEST";
export const GET_SUBCATEGORY_SUCCESS = "GET_SUBCATEGORY_SUCCESS";
export const GET_SUBCATEGORY_FAILURE = "GET_SUBCATEGORY_FAILURE";

export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAILURE = "ADD_SUBCATEGORY_FAILURE";

export const EDIT_SUBCATEGORY_REQUEST = "EDIT_SUBCATEGORY_REQUEST";
export const EDIT_SUBCATEGORY_SUCCESS = "EDIT_SUBCATEGORY_SUCCESS";
export const EDIT_SUBCATEGORY_FAILURE = "EDIT_SUBCATEGORY_FAILURE";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAILURE = "DELETE_SUBCATEGORY_FAILURE";

export const GET_SUBCATEGORY_BY_ID_REQUEST = "GET_SUBCATEGORY_BY_ID_REQUEST";
export const GET_SUBCATEGORY_BY_ID_SUCCESS = "GET_SUBCATEGORY_BY_ID_SUCCESS";
export const GET_SUBCATEGORY_BY_ID_FAILURE = "GET_SUBCATEGORY_BY_ID_FAILURE";

export const FIND_SUBCATEGORY_BY_KEYWORD_REQUEST = "FIND_SUBCATEGORY_BY_KEYWORD_REQUEST";
export const FIND_SUBCATEGORY_BY_KEYWORD_SUCCESS = "FIND_SUBCATEGORY_BY_KEYWORD_SUCCESS";
export const FIND_SUBCATEGORY_BY_KEYWORD_FAILURE = "FIND_SUBCATEGORY_BY_KEYWORD_FAILURE";
